"""Seed the catalog from the Exicom pricebook.

AUTO-GENERATED by scripts/build_seed_from_pricebook.py — do not edit by hand.
Each product carries a multi-currency / multi-tier (MoQ) price matrix in
`prices`: { currency: [[min_qty, max_qty_or_None, price], ...] }.

NOTE: the EUR / EUR_ND figures for the 12 AC Charger products with a Part
Code (HE518585, HE518581, HE531505, HE531502, HE531503, HE531504, HE531296,
HE531501) were hand-updated from "pricing book euro.xlsx" (40%/43.5%/47%
MoQ discount tiers off list price). A future regen from the master
pricebook must carry these same EUR numbers forward or they'll be lost.

Run idempotently:        python -m app.seed
Wipe & reload catalog:   python -m app.seed --reset
"""
import sys

from app.database import SessionLocal, Base, engine
from app import models, migrate

SEED_PRODUCTS = [
    dict(
        product_code='HE518585',
        code_note='AC Charger',
        product_name='Spin Air 22 kW (Wifi, RFID and Modem)',
        description='',
        unit_price=360.0,
        currency='USD',
        unit='Nos.',
        category='AC Charger',
        prices={'USD': [[1, 50, 360.0], [51, 150, 339.0], [151, None, 318.0]], 'EUR': [[1, 50, 315.47], [51, 150, 297.07], [151, None, 278.66]], 'MYR': [[1, None, 3272.0]], 'EUR_ND': [[1, None, 525.78]]},
    ),
    dict(
        product_code='HE518585',
        code_note='AC Charger',
        product_name='Spin Air 22 kW (Wifi and RFID)',
        description='',
        unit_price=351.0,
        currency='USD',
        unit='Nos.',
        category='AC Charger',
        prices={'USD': [[1, 50, 351.0], [51, 150, 330.52], [151, None, 310.05]], 'EUR': [[1, 50, 307.58], [51, 150, 289.64], [151, None, 271.7]], 'EUR_ND': [[1, None, 512.64]]},
    ),
    dict(
        product_code='HE518585',
        code_note='AC Charger',
        product_name='Spin Air 22 kW (Wifi)',
        description='',
        unit_price=342.0,
        currency='USD',
        unit='Nos.',
        category='AC Charger',
        prices={'USD': [[1, 50, 342.0], [51, 150, 322.05], [151, None, 302.1]], 'EUR': [[1, 50, 299.69], [51, 150, 282.21], [151, None, 264.73]], 'EUR_ND': [[1, None, 499.49]]},
    ),
    dict(
        product_code='HE518581',
        code_note='AC Charger',
        product_name='Spin Air 7.5 kW (Wifi, RFID and Modem)',
        description='',
        unit_price=276.0,
        currency='USD',
        unit='Nos.',
        category='AC Charger',
        prices={'USD': [[1, 50, 276.0], [51, 150, 259.9], [151, None, 243.8]], 'EUR': [[1, 50, 241.86], [51, 150, 227.75], [151, None, 213.64]], 'MYR': [[1, None, 2337.0]], 'EUR_ND': [[1, None, 403.1]]},
    ),
    dict(
        product_code='HE518581',
        code_note='AC Charger',
        product_name='Spin Air 7.5 kW (Wifi and RFID)',
        description='',
        unit_price=267.0,
        currency='USD',
        unit='Nos.',
        category='AC Charger',
        prices={'USD': [[1, 50, 267.0], [51, 150, 251.42], [151, None, 235.85]], 'EUR': [[1, 50, 233.97], [51, 150, 220.32], [151, None, 206.67]], 'EUR_ND': [[1, None, 389.95]]},
    ),
    dict(
        product_code='HE518581',
        code_note='AC Charger',
        product_name='Spin Air 7.5 kW (Wifi)',
        description='',
        unit_price=258.0,
        currency='USD',
        unit='Nos.',
        category='AC Charger',
        prices={'USD': [[1, 50, 258.0], [51, 150, 242.95], [151, None, 227.9]], 'EUR': [[1, 50, 226.09], [51, 150, 212.9], [151, None, 199.71]], 'EUR_ND': [[1, None, 376.81]]},
    ),
    dict(
        product_code='HE531505',
        code_note='AC Charger',
        product_name='Spin Air 7 kW - UL (Wifi, RFID, Modem and Ethernet)',
        description='Input: NEMA - 14-50p ( 4 Pin ) plug\nOutput: NACS',
        unit_price=360.0,
        currency='USD',
        unit='Nos.',
        category='AC Charger',
        prices={'USD': [[1, 50, 360.0], [51, 150, 339.0], [151, None, 318.0]], 'EUR': [[1, 50, 315.47], [51, 150, 297.07], [151, None, 278.66]], 'EUR_ND': [[1, None, 525.78]]},
    ),
    dict(
        product_code='HE531502',
        code_note='AC Charger',
        product_name='Spin Air 9 kW - UL (Wifi, RFID, Modem and Ethernet)',
        description='Input: NEMA - 6-50p ( 3 Pin ) plug\nOutput: Type 1',
        unit_price=414.0,
        currency='USD',
        unit='Nos.',
        category='AC Charger',
        prices={'USD': [[1, 50, 414.0], [51, 150, 389.85], [151, None, 365.7]], 'EUR': [[1, 50, 362.79], [51, 150, 341.63], [151, None, 320.46]], 'EUR_ND': [[1, None, 604.65]]},
    ),
    dict(
        product_code='HE531503',
        code_note='AC Charger',
        product_name='Spin Air 9 kW - UL (Wifi, RFID, Modem and Ethernet)',
        description='Input: NEMA - 14-50p ( 4 Pin ) plug\nOutput: Type 1',
        unit_price=414.0,
        currency='USD',
        unit='Nos.',
        category='AC Charger',
        prices={'USD': [[1, 50, 414.0], [51, 150, 389.85], [151, None, 365.7]], 'EUR': [[1, 50, 362.79], [51, 150, 341.63], [151, None, 320.46]], 'EUR_ND': [[1, None, 604.65]]},
    ),
    dict(
        product_code='HE531504',
        code_note='AC Charger',
        product_name='Spin Air 9 kW - UL (Wifi, RFID, Modem and Ethernet)',
        description='Input: NEMA - 14-50p ( 4 Pin ) plug\nOutput: NACS',
        unit_price=366.0,
        currency='USD',
        unit='Nos.',
        category='AC Charger',
        prices={'USD': [[1, 50, 366.0], [51, 150, 344.65], [151, None, 323.3]], 'EUR': [[1, 50, 320.72], [51, 150, 302.02], [151, None, 283.31]], 'EUR_ND': [[1, None, 534.54]]},
    ),
    dict(
        product_code='HE531296',
        code_note='AC Charger',
        product_name='Spin Air 11 kW - UL (Wifi, RFID, Modem and Ethernet)',
        description='Input: Hardwire\nOutput: Type 1',
        unit_price=456.0,
        currency='USD',
        unit='Nos.',
        category='AC Charger',
        prices={'USD': [[1, 50, 456.0], [51, 150, 429.4], [151, None, 402.8]], 'EUR': [[1, 50, 399.59], [51, 150, 376.28], [151, None, 352.97]], 'EUR_ND': [[1, None, 665.99]]},
    ),
    dict(
        product_code='HE531501',
        code_note='AC Charger',
        product_name='Spin Air 11 kW - UL (Wifi, RFID, Modem and Ethernet)',
        description='Input: Hardwire\nOutput: NACS',
        unit_price=384.0,
        currency='USD',
        unit='Nos.',
        category='AC Charger',
        prices={'USD': [[1, 50, 384.0], [51, 150, 361.6], [151, None, 339.2]], 'EUR': [[1, 50, 336.5], [51, 150, 316.87], [151, None, 297.24]], 'EUR_ND': [[1, None, 560.83]]},
    ),
    dict(
        product_code='HE531324',
        code_note='AC Charger',
        product_name='Spin Free 3.3 kW',
        description='',
        unit_price=85.0,
        currency='USD',
        unit='Nos.',
        category='AC Charger',
        prices={'USD': [[1, 50, 85.0], [51, 150, 80.0], [151, None, 75.0]], 'EUR': [[1, 50, 73.1], [51, 150, 68.8], [151, None, 64.5]]},
    ),
    dict(
        product_code='HE531097',
        code_note='AC Charger',
        product_name='Spin Air 22 kW (Wifi, RFID, Modem and Ethernet)',
        description='',
        unit_price=27550.0,
        currency='INR',
        unit='Nos.',
        category='AC Charger',
        prices={'INR': [[1, 50, 27550.0], [51, 150, 26125.0], [151, None, 24700.0]]},
    ),
    dict(
        product_code='HE531125',
        code_note='AC Charger',
        product_name='Spin Air 22 kW (Wifi, RFID and Modem)',
        description='',
        unit_price=25650.0,
        currency='INR',
        unit='Nos.',
        category='AC Charger',
        prices={'INR': [[1, 50, 25650.0], [51, 150, 24225.0], [151, None, 22800.0]]},
    ),
    dict(
        product_code='HE531126',
        code_note='AC Charger',
        product_name='Spin Air 22 kW (Wifi and RFID)',
        description='',
        unit_price=24700.0,
        currency='INR',
        unit='Nos.',
        category='AC Charger',
        prices={'INR': [[1, 50, 24700.0], [51, 150, 23275.0], [151, None, 21850.0]]},
    ),
    dict(
        product_code='HE531121',
        code_note='AC Charger',
        product_name='Spin Air 22 kW (Wifi)',
        description='',
        unit_price=23750.0,
        currency='INR',
        unit='Nos.',
        category='AC Charger',
        prices={'INR': [[1, 50, 23750.0], [51, 150, 22325.0], [151, None, 20900.0]]},
    ),
    dict(
        product_code='HE531098',
        code_note='AC Charger',
        product_name='Spin Air 7.5 kW (Wifi, RFID, Modem and Ethernet)',
        description='',
        unit_price=19475.0,
        currency='INR',
        unit='Nos.',
        category='AC Charger',
        prices={'INR': [[1, 50, 19475.0], [51, 150, 18525.0], [151, None, 17575.0]]},
    ),
    dict(
        product_code='HE531122',
        code_note='AC Charger',
        product_name='Spin Air 7.5 kW (Wifi, RFID and Modem)',
        description='',
        unit_price=17575.0,
        currency='INR',
        unit='Nos.',
        category='AC Charger',
        prices={'INR': [[1, 50, 17575.0], [51, 150, 16625.0], [151, None, 15675.0]]},
    ),
    dict(
        product_code='HE531123',
        code_note='AC Charger',
        product_name='Spin Air 7.5 kW (Wifi and RFID)',
        description='',
        unit_price=16625.0,
        currency='INR',
        unit='Nos.',
        category='AC Charger',
        prices={'INR': [[1, 50, 16625.0], [51, 150, 15675.0], [151, None, 14725.0]]},
    ),
    dict(
        product_code='HE531124',
        code_note='AC Charger',
        product_name='Spin Air 7.5 kW (Wifi)',
        description='',
        unit_price=15675.0,
        currency='INR',
        unit='Nos.',
        category='AC Charger',
        prices={'INR': [[1, 50, 15675.0], [51, 150, 14725.0], [151, None, 13775.0]]},
    ),
    dict(
        product_code='HE531234',
        code_note='AC Charger',
        product_name='Spin Free 3.3 kW',
        description='',
        unit_price=8075.0,
        currency='INR',
        unit='Nos.',
        category='AC Charger',
        prices={'INR': [[1, 50, 8075.0], [51, 150, 7600.0], [151, None, 7125.0]]},
    ),
    dict(
        product_code='HE518581',
        code_note='Accessories',
        product_name='AC-Spare Kit for 7.5 kW charger',
        description='',
        unit_price=420.0,
        currency='USD',
        unit='Nos.',
        category='Accessories',
        prices={'USD': [[1, None, 420.0]], 'EUR': [[1, None, 360.0]]},
    ),
    dict(
        product_code='HE518583',
        code_note='Accessories',
        product_name='AC-Spare Kit for 11 kW charger',
        description='',
        unit_price=420.0,
        currency='USD',
        unit='Nos.',
        category='Accessories',
        prices={'USD': [[1, None, 420.0]], 'EUR': [[1, None, 360.0]]},
    ),
    dict(
        product_code='HE518585',
        code_note='Accessories',
        product_name='AC-Spare Kit for 22 kW charger',
        description='',
        unit_price=420.0,
        currency='USD',
        unit='Nos.',
        category='Accessories',
        prices={'USD': [[1, None, 420.0]], 'EUR': [[1, None, 360.0]]},
    ),
    dict(
        product_code='HE521683',
        code_note='Accessories',
        product_name='Load Balancing Kit (Single Charger) - Single Phase',
        description='',
        unit_price=210.0,
        currency='USD',
        unit='Nos.',
        category='Accessories',
        prices={'USD': [[1, None, 210.0]], 'EUR': [[1, None, 176.4]]},
    ),
    dict(
        product_code='HE521684',
        code_note='Accessories',
        product_name='Load Balancing Kit (Single Charger) - Three Phase',
        description='',
        unit_price=165.0,
        currency='USD',
        unit='Nos.',
        category='Accessories',
        prices={'USD': [[1, None, 165.0]], 'EUR': [[1, None, 138.6]]},
    ),
    dict(
        product_code='HE-INCABLE',
        code_note='Accessories',
        product_name='Input Cable (1.5 m)',
        description='',
        unit_price=10,
        currency='USD',
        unit='Nos.',
        category='Accessories',
        prices={'USD': [[1, None, 10]], 'EUR': [[1, None, 10]], 'INR': [[1, None, 850]], 'MYR': [[1, None, 45]]},
    ),
]


def _rounded(p: dict) -> dict:
    """Round unit_price and every price-tier value to the nearest whole number.

    SEED_PRODUCTS keeps the pricebook's exact decimal figures for reference;
    this is applied at seed time so what actually lands in the catalog (and
    from there, every order/PDF) is always a whole number.
    """
    out = dict(p)
    out["unit_price"] = round(out["unit_price"])
    if out.get("prices"):
        out["prices"] = {
            cur: [[lo, hi, round(price)] for lo, hi, price in tiers]
            for cur, tiers in out["prices"].items()
        }
    return out


def main(reset: bool = False) -> None:
    # Tables first, then column/data migrations — migrate.run() queries tables
    # (e.g. the fulfillment stage tracker) that only exist after create_all.
    Base.metadata.create_all(bind=engine)
    migrate.run()
    db = SessionLocal()
    try:
        if reset:
            deleted = db.query(models.CatalogProduct).delete()
            db.commit()
            print(f"Reset: removed {deleted} existing catalog products.")

        inserted = updated = 0
        for raw in SEED_PRODUCTS:
            p = _rounded(raw)
            obj = (
                db.query(models.CatalogProduct)
                .filter_by(product_code=p["product_code"], product_name=p["product_name"])
                .first()
            )
            if obj:
                for k, v in p.items():
                    setattr(obj, k, v)
                updated += 1
            else:
                db.add(models.CatalogProduct(**p))
                inserted += 1
        db.commit()
        print(f"Catalog seed complete: {inserted} inserted, {updated} updated.")
    finally:
        db.close()

    # Seed per-country logistics rates alongside the catalog.
    from app import seed_logistics
    seed_logistics.run(reset=reset)


if __name__ == "__main__":
    main(reset="--reset" in sys.argv)

